Added txt as md plugin
obsidianmd/obsidian-releases pull request #160
Opened 2021-02-09 01:21 UTC by deathau

2021-02-09 03:16 UTC, liamcain commented on community-plugins.json
> +        "description": "Edit ini files in Obsidian",
Wrong description 😄

2021-02-09 03:27 UTC, deathau commented on community-plugins.json
> +        "description": "Edit ini files in Obsidian",
Whoops. Thanks for the catch

2021-02-09 14:40 UTC, lishid requested changes

2021-02-09 14:40 UTC, lishid commented on community-plugins.json
> +    },
Might need to remove this extra comma

2021-02-10 01:09 UTC, deathau commented on community-plugins.json
> +    },
done

2021-02-10 02:49 UTC, merged